version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: festival-postgres
    environment:
      POSTGRES_DB: festival_db
      POSTGRES_USER: festival_user
      POSTGRES_PASSWORD: festival_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./server/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U festival_user -d festival_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: