/**
 * Per-movie Drive file management: /api/movies/:movieId/files
 *
 * Mounted with mergeParams so :movieId is available. Drive-dependent endpoints
 * return 503 when Google Drive is not configured; GET degrades to DB rows with
 * a drive_error flag so the UI always renders known status.
 */

const express = require('express');
const { pool } = require('../models/database');
const { logError } = require('../utils/logger');
const googleDrive = require('../services/googleDrive');
const { proxyDriveMedia } = require('../services/driveMediaProxy');
const transcodeQueue = require('../services/transcodeQueue');
const {
  convertSrtToVtt,
  parseSubtitles,
  serializeSrt,
  serializeVtt,
} = require('../utils/subtitles');
const { scanMovie, upsertFileRow } = require('../services/movieFileScanner');
const {
  MAX_SUBTITLE_BYTES,
  readSubtitleText,
  cacheSubtitleTextSafe,
} = require('../services/subtitleCache');
const {
  conventionFileName,
  detachedFileName,
  extensionOf,
  isVideoFile,
  SUBTITLE_EXTENSIONS,
  FILE_KINDS,
} = require('../utils/movieFileNaming');

const router = express.Router({ mergeParams: true });

const SUBTITLE_KINDS = ['subtitles_cs', 'subtitles_en'];
// Languages accepted by the /subtitles/:lang routes (subtitles_{lang} kinds).
// Synced variants are machine-generated by the sync worker but serve/edit the same way.
const SUBTITLE_LANGS = ['cs', 'en', 'cs_synced', 'en_synced'];
// File kinds that are playable video and can be streamed to the browser.
const STREAMABLE_KINDS = ['movie', 'movie_proxy'];

function notConfigured(res) {
  return res.status(503).json({ error: 'Google Drive is not configured' });
}

/** Drive "file not found" (already deleted/trashed elsewhere). */
function isDriveNotFound(error) {
  return error?.code === 404 || error?.response?.status === 404;
}

/** The manual "files ready" mark from a loadMovie() row, or null. */
function readyOf(movie) {
  return movie.files_ready_at
    ? { at: movie.files_ready_at, by: movie.files_ready_by || null }
    : null;
}

/**
 * Ensure a file's type matches the kind slot it will occupy:
 * subtitle kinds require .srt/.vtt; the movie kind requires a video file.
 * Returns an error string, or null if valid.
 */
function validateKindForFile(fileKind, fileName, mimeType) {
  const ext = extensionOf(fileName);
  if (
    (SUBTITLE_KINDS.includes(fileKind) || fileKind.endsWith('_synced')) &&
    !SUBTITLE_EXTENSIONS.includes(ext)
  ) {
    return 'Subtitles must be .srt or .vtt';
  }
  if (fileKind === 'movie' && !isVideoFile(fileName, mimeType)) {
    return 'Movie asset must be a video file';
  }
  if (fileKind === 'movie_proxy' && ext !== 'mp4') {
    return 'Preview proxy must be an .mp4';
  }
  return null;
}

/** Load a movie row with edition_year, or null. */
async function loadMovie(movieId) {
  const res = await pool.query(
    `SELECT m.id, m.name_cs, m.name_en, m.drive_folder_id, m.files_ready_at,
            m.files_ready_by, e.year AS edition_year
     FROM movies m JOIN editions e ON m.edition_id = e.id
     WHERE m.id = $1`,
    [movieId]
  );
  return res.rows[0] || null;
}

function subtitleMime(ext) {
  return ext === 'vtt' ? 'text/vtt' : 'application/x-subrip';
}

/** Read a subtitle row's text through the cache (Drive only on a miss). */
function readRowText(row) {
  return readSubtitleText(row.drive_file_id, { expectedMd5: row.md5_checksum || null });
}

/** Cache freshly written subtitle bytes; failures are only logged. */
function cacheWritten(req, movieId, meta, body) {
  return cacheSubtitleTextSafe(
    meta.id,
    { bytes: body, md5: meta.md5Checksum || null },
    (cacheError) => logError(cacheError, req, { operation: 'cache_subtitle_text', movieId })
  );
}

/**
 * Guard an in-place overwrite: compare the file's current Drive md5 with the
 * md5 the app based its change on. On a mismatch the file was edited outside
 * the app — refresh the pointer row (so the next read re-downloads instead of
 * serving the cached old text) and return the fresh metadata as `changed`.
 */
async function checkDriveUnchanged(movieId, row, baseMd5) {
  const meta = await googleDrive.getFileMetadata(row.drive_file_id);
  if (meta.md5Checksum && baseMd5 && meta.md5Checksum !== baseMd5) {
    await upsertFileRow(movieId, row.file_kind, meta);
    return { changed: meta };
  }
  return { changed: null };
}

/**
 * Mark a subtitle track's open quality flags stale (its file was replaced or
 * removed, so the findings no longer describe it). Non-fatal.
 */
async function staleOpenFlags(req, movieId, lang) {
  try {
    await pool.query(
      `UPDATE subtitle_quality_flags SET status = 'stale'
       WHERE movie_id = $1 AND lang = $2 AND status = 'open'`,
      [movieId, lang]
    );
  } catch (flagError) {
    logError(flagError, req, { operation: 'stale_subtitle_quality_flags', movieId });
  }
}

/** Load the movie_files row for a subtitle language, or null. */
async function loadSubtitleRow(movieId, lang) {
  const row = await pool.query(
    'SELECT * FROM movie_files WHERE movie_id = $1 AND file_kind = $2',
    [movieId, `subtitles_${lang}`]
  );
  return row.rows[0] || null;
}

// GET / — DB rows always; live folder listing + unclassified when Drive is up.
router.get('/', async (req, res) => {
  const { movieId } = req.params;
  try {
    const movie = await loadMovie(movieId);
    if (!movie) return res.status(404).json({ error: 'Movie not found' });

    if (!googleDrive.isConfigured()) {
      const dbRows = await pool.query(
        'SELECT * FROM movie_files WHERE movie_id = $1 ORDER BY file_kind',
        [movieId]
      );
      return res.json({
        files: dbRows.rows,
        folder: movie.drive_folder_id ? { id: movie.drive_folder_id } : null,
        unclassified: [],
        drive_configured: false,
        ready: readyOf(movie),
      });
    }

    // Live scan reconciles rows and surfaces unclassified files.
    try {
      const result = await scanMovie(movieId);
      return res.json({ ...result, drive_configured: true, ready: readyOf(movie) });
    } catch (driveError) {
      logError(driveError, req, { operation: 'movie_files_scan', movieId });
      const dbRows = await pool.query(
        'SELECT * FROM movie_files WHERE movie_id = $1 ORDER BY file_kind',
        [movieId]
      );
      return res.json({
        files: dbRows.rows,
        folder: movie.drive_folder_id ? { id: movie.drive_folder_id } : null,
        unclassified: [],
        drive_configured: true,
        drive_error: driveError.message,
        ready: readyOf(movie),
      });
    }
  } catch (error) {
    logError(error, req, { operation: 'get_movie_files', movieId });
    res.status(500).json({ error: error.message });
  }
});

// POST /folder — ensure the Drive folder exists for this movie.
router.post('/folder', async (req, res) => {
  const { movieId } = req.params;
  if (!googleDrive.isConfigured()) return notConfigured(res);
  try {
    const movie = await loadMovie(movieId);
    if (!movie) return res.status(404).json({ error: 'Movie not found' });
    const folderId = await googleDrive.ensureMovieFolder(movie);
    res.json({ folder: { id: folderId } });
  } catch (error) {
    logError(error, req, { operation: 'ensure_movie_folder', movieId });
    res.status(500).json({ error: error.message });
  }
});

// POST /rescan — reconcile rows against Drive on demand.
router.post('/rescan', async (req, res) => {
  const { movieId } = req.params;
  if (!googleDrive.isConfigured()) return notConfigured(res);
  try {
    const result = await scanMovie(movieId);
    res.json({ ...result, drive_configured: true });
  } catch (error) {
    logError(error, req, { operation: 'rescan_movie_files', movieId });
    res.status(error.statusCode || 500).json({ error: error.message });
  }
});

// POST /upload-session — create a resumable session for a big file upload.
router.post('/upload-session', async (req, res) => {
  const { movieId } = req.params;
  if (!googleDrive.isConfigured()) return notConfigured(res);
  try {
    const { file_kind, file_name, file_size, mime_type } = req.body;
    if (!FILE_KINDS.includes(file_kind)) {
      return res.status(400).json({ error: 'Invalid file_kind' });
    }
    const kindError = validateKindForFile(file_kind, file_name, mime_type);
    if (kindError) return res.status(400).json({ error: kindError });

    const movie = await loadMovie(movieId);
    if (!movie) return res.status(404).json({ error: 'Movie not found' });

    const folderId = await googleDrive.ensureMovieFolder(movie);
    const ext = extensionOf(file_name) || 'bin';
    const targetName = conventionFileName(movie, file_kind, ext);
    const origin = req.get('origin') || process.env.APP_URL;

    const uploadUrl = await googleDrive.createResumableSession({
      folderId,
      name: targetName,
      mimeType: mime_type,
      size: file_size,
      origin,
    });
    res.json({ upload_url: uploadUrl, target_name: targetName });
  } catch (error) {
    logError(error, req, { operation: 'create_upload_session', movieId });
    res.status(500).json({ error: error.message });
  }
});

// POST /upload-complete — verify the uploaded file and record the pointer row.
router.post('/upload-complete', async (req, res) => {
  const { movieId } = req.params;
  if (!googleDrive.isConfigured()) return notConfigured(res);
  try {
    const { file_kind, drive_file_id } = req.body;
    if (!FILE_KINDS.includes(file_kind)) {
      return res.status(400).json({ error: 'Invalid file_kind' });
    }
    if (!drive_file_id) {
      return res.status(400).json({ error: 'drive_file_id is required' });
    }
    const movie = await loadMovie(movieId);
    if (!movie) return res.status(404).json({ error: 'Movie not found' });
    if (!movie.drive_folder_id) {
      return res.status(400).json({ error: 'Movie has no Drive folder' });
    }

    const meta = await googleDrive.getFileMetadata(drive_file_id);
    // Only record files that actually live in this movie's folder.
    if (!meta.parents || !meta.parents.includes(movie.drive_folder_id)) {
      return res.status(400).json({ error: 'File is not in this movie folder' });
    }
    const kindError = validateKindForFile(file_kind, meta.name, meta.mimeType);
    if (kindError) return res.status(400).json({ error: kindError });

    await upsertFileRow(movieId, file_kind, meta);
    // A newly-uploaded master gets a preview proxy generated automatically.
    // Awaited so the job row exists before we respond (the client reloads the
    // player right after and needs to see the pending job to start polling).
    if (file_kind === 'movie') {
      await transcodeQueue.enqueueForMovie(movieId, req.user?.email);
    }
    const row = await pool.query(
      'SELECT * FROM movie_files WHERE movie_id = $1 AND file_kind = $2',
      [movieId, file_kind]
    );
    res.json({ file: row.rows[0] });
  } catch (error) {
    logError(error, req, { operation: 'upload_complete', movieId });
    res.status(500).json({ error: error.message });
  }
});

// POST /subtitles — small subtitle upload through the backend (base64).
router.post('/subtitles', async (req, res) => {
  const { movieId } = req.params;
  if (!googleDrive.isConfigured()) return notConfigured(res);
  try {
    const { file_kind, file_name, content_base64 } = req.body;
    if (!SUBTITLE_KINDS.includes(file_kind)) {
      return res.status(400).json({ error: 'file_kind must be a subtitle kind' });
    }
    const ext = extensionOf(file_name);
    if (!SUBTITLE_EXTENSIONS.includes(ext)) {
      return res.status(400).json({ error: 'Subtitles must be .srt or .vtt' });
    }
    if (!content_base64) {
      return res.status(400).json({ error: 'content_base64 is required' });
    }

    const movie = await loadMovie(movieId);
    if (!movie) return res.status(404).json({ error: 'Movie not found' });

    const folderId = await googleDrive.ensureMovieFolder(movie);
    const targetName = conventionFileName(movie, file_kind, ext);
    const body = Buffer.from(content_base64, 'base64');

    const prior = await loadSubtitleRow(movieId, file_kind.replace('subtitles_', ''));
    const created = await googleDrive.uploadSmallFile({
      folderId,
      name: targetName,
      mimeType: subtitleMime(ext),
      body,
    });
    await upsertFileRow(movieId, file_kind, created);
    await cacheWritten(req, movieId, created, body);
    // Replacing: trash the old file, otherwise it lingers under the same
    // convention name and the scanner re-adopts it once this one is removed.
    if (prior && prior.drive_file_id !== created.id) {
      await googleDrive.trashFile(prior.drive_file_id).catch((trashError) => {
        if (!isDriveNotFound(trashError)) {
          logError(trashError, req, { operation: 'trash_replaced_subtitles', movieId });
        }
      });
    }
    if (prior) await staleOpenFlags(req, movieId, file_kind.replace('subtitles_', ''));
    const row = await pool.query(
      'SELECT * FROM movie_files WHERE movie_id = $1 AND file_kind = $2',
      [movieId, file_kind]
    );
    res.json({ file: row.rows[0] });
  } catch (error) {
    logError(error, req, { operation: 'upload_subtitles', movieId });
    res.status(500).json({ error: error.message });
  }
});

// POST /import — classify a file already sitting in the movie folder.
router.post('/import', async (req, res) => {
  const { movieId } = req.params;
  if (!googleDrive.isConfigured()) return notConfigured(res);
  try {
    const { drive_file_id, file_kind, rename, replace } = req.body;
    if (!FILE_KINDS.includes(file_kind)) {
      return res.status(400).json({ error: 'Invalid file_kind' });
    }
    if (!drive_file_id) {
      return res.status(400).json({ error: 'drive_file_id is required' });
    }
    const movie = await loadMovie(movieId);
    if (!movie) return res.status(404).json({ error: 'Movie not found' });
    if (!movie.drive_folder_id) {
      return res.status(400).json({ error: 'Movie has no Drive folder' });
    }

    let meta = await googleDrive.getFileMetadata(drive_file_id);
    if (!meta.parents || !meta.parents.includes(movie.drive_folder_id)) {
      return res
        .status(400)
        .json({ error: 'File is not in this movie folder' });
    }
    const kindError = validateKindForFile(file_kind, meta.name, meta.mimeType);
    if (kindError) return res.status(400).json({ error: kindError });

    // 409 if the kind is already occupied, unless replace is requested.
    const occupied = await pool.query(
      'SELECT id, drive_file_id FROM movie_files WHERE movie_id = $1 AND file_kind = $2',
      [movieId, file_kind]
    );
    if (occupied.rows.length > 0 && occupied.rows[0].drive_file_id !== drive_file_id && !replace) {
      return res.status(409).json({ error: 'This asset kind is already set' });
    }

    if (rename) {
      const ext = extensionOf(meta.name) || 'bin';
      const targetName = conventionFileName(movie, file_kind, ext);
      if (targetName !== meta.name) {
        meta = await googleDrive.renameFile(drive_file_id, targetName);
        meta = await googleDrive.getFileMetadata(drive_file_id);
      }
    }

    await upsertFileRow(movieId, file_kind, meta);
    // Importing a master as the movie kicks off proxy generation. Awaited so the
    // job row exists before we respond (the client reloads the player right after
    // and needs to see the pending job to start polling).
    if (file_kind === 'movie') {
      await transcodeQueue.enqueueForMovie(movieId, req.user?.email);
    }
    const row = await pool.query(
      'SELECT * FROM movie_files WHERE movie_id = $1 AND file_kind = $2',
      [movieId, file_kind]
    );
    res.json({ file: row.rows[0] });
  } catch (error) {
    logError(error, req, { operation: 'import_movie_file', movieId });
    res.status(500).json({ error: error.message });
  }
});

// GET /stream/:fileKind — proxy the movie/proxy file bytes with Range support.
router.get('/stream/:fileKind', async (req, res) => {
  const { movieId, fileKind } = req.params;
  if (!STREAMABLE_KINDS.includes(fileKind)) {
    return res.status(400).json({ error: 'Not a streamable file kind' });
  }
  if (!googleDrive.isConfigured()) return notConfigured(res);
  try {
    const row = await pool.query(
      'SELECT drive_file_id, mime_type FROM movie_files WHERE movie_id = $1 AND file_kind = $2',
      [movieId, fileKind]
    );
    if (row.rows.length === 0) return res.status(404).json({ error: 'File not found' });
    await proxyDriveMedia(req, res, row.rows[0].drive_file_id, row.rows[0].mime_type || 'video/mp4');
  } catch (error) {
    logError(error, req, { operation: 'stream_movie_file', movieId });
    if (!res.headersSent) res.status(500).json({ error: error.message });
  }
});

// GET /subtitles/:lang — download the subtitle from Drive and serve it as VTT.
router.get('/subtitles/:lang', async (req, res) => {
  const { movieId, lang } = req.params;
  const cleanLang = String(lang).replace(/\.vtt$/i, '');
  if (!SUBTITLE_LANGS.includes(cleanLang)) {
    return res.status(400).json({ error: 'Unsupported subtitle language' });
  }
  if (!googleDrive.isConfigured()) return notConfigured(res);
  try {
    const row = await loadSubtitleRow(movieId, cleanLang);
    if (!row) return res.status(404).json({ error: 'Subtitles not found' });

    const { text } = await readRowText(row);
    const vtt = extensionOf(row.file_name) === 'vtt' ? text : convertSrtToVtt(text);

    res.setHeader('Content-Type', 'text/vtt; charset=utf-8');
    res.send(vtt);
  } catch (error) {
    if (error.statusCode === 413) {
      return res.status(413).json({ error: error.message });
    }
    logError(error, req, { operation: 'get_subtitles', movieId });
    if (!res.headersSent) res.status(500).json({ error: error.message });
  }
});

// GET /subtitles/:lang/cues — parsed subtitle cues as JSON, for the editor.
router.get('/subtitles/:lang/cues', async (req, res) => {
  const { movieId, lang } = req.params;
  if (!SUBTITLE_LANGS.includes(lang)) {
    return res.status(400).json({ error: 'Unsupported subtitle language' });
  }
  if (!googleDrive.isConfigured()) return notConfigured(res);
  try {
    const row = await loadSubtitleRow(movieId, lang);
    if (!row) return res.status(404).json({ error: 'Subtitles not found' });

    const ext = extensionOf(row.file_name);
    const { text, md5, source, driveError } = await readRowText(row);
    let cues;
    try {
      cues = parseSubtitles(text, ext);
    } catch (parseError) {
      return res.status(422).json({ error: parseError.message });
    }

    res.json({
      file: {
        file_name: row.file_name,
        drive_file_id: row.drive_file_id,
        // The md5 of the text actually returned — the editor saves against it.
        md5_checksum: md5,
        drive_modified_at: row.drive_modified_at,
      },
      format: ext === 'vtt' ? 'vtt' : 'srt',
      cues,
      // 'stale-cache': Drive refused the download, this is the last cached copy.
      cache: { source, drive_error: driveError || null },
    });
  } catch (error) {
    if (error.statusCode === 413) {
      return res.status(413).json({ error: error.message });
    }
    logError(error, req, { operation: 'get_subtitle_cues', movieId });
    if (!res.headersSent) res.status(500).json({ error: error.message });
  }
});

// Timing lines are copied verbatim from the parsed source, so accept the SRT
// form with optional trailing cue settings/coordinates.
const CUE_TIMING_RE =
  /^\d{1,2}:\d{2}:\d{2}[,.]\d{1,3}\s+-->\s+\d{1,2}:\d{2}:\d{2}[,.]\d{1,3}(\s.*)?$/;

// PUT /subtitles/:lang/cues — save edited cue texts back to the Drive file
// in place (same file id). Timings are never changed by the editor.
router.put('/subtitles/:lang/cues', async (req, res) => {
  const { movieId, lang } = req.params;
  if (!SUBTITLE_LANGS.includes(lang)) {
    return res.status(400).json({ error: 'Unsupported subtitle language' });
  }
  if (!googleDrive.isConfigured()) return notConfigured(res);
  try {
    const { cues, base_md5 } = req.body || {};
    if (!Array.isArray(cues) || cues.length === 0) {
      return res.status(400).json({ error: 'cues must be a non-empty array' });
    }
    if (!base_md5) {
      return res.status(400).json({ error: 'base_md5 is required' });
    }
    for (const cue of cues) {
      if (
        !cue ||
        typeof cue.timing !== 'string' ||
        !CUE_TIMING_RE.test(cue.timing.trim()) ||
        typeof cue.text !== 'string'
      ) {
        return res
          .status(400)
          .json({ error: 'Each cue needs a valid timing line and a text string' });
      }
    }

    const row = await loadSubtitleRow(movieId, lang);
    if (!row) return res.status(404).json({ error: 'Subtitles not found' });

    // The file must still be exactly what the editor loaded — otherwise
    // someone changed it on Drive outside the app and saving would wipe that.
    const { changed } = await checkDriveUnchanged(movieId, row, base_md5);
    if (changed) {
      return res.status(409).json({
        error:
          'Subtitles were changed on Drive outside the app since you loaded them. ' +
          'Reload the editor to get the current version (your unsaved edits will be lost).',
      });
    }

    const ext = extensionOf(row.file_name);
    const clean = cues.map((c) => ({ timing: c.timing.trim(), text: c.text }));
    const text = ext === 'vtt' ? serializeVtt(clean) : serializeSrt(clean);
    const body = Buffer.from(text, 'utf8');
    if (body.length > MAX_SUBTITLE_BYTES) {
      return res.status(413).json({ error: 'Subtitles file is too large' });
    }

    const updated = await googleDrive.updateFileContent({
      fileId: row.drive_file_id,
      mimeType: subtitleMime(ext),
      body,
    });
    await upsertFileRow(movieId, row.file_kind, updated);
    await cacheWritten(req, movieId, updated, body);
    const fresh = await loadSubtitleRow(movieId, lang);

    // Reconcile open quality flags against the saved text (non-fatal):
    // suggestion applied -> accepted; text changed some other way (or the
    // file shape changed) -> stale; untouched -> stays open, re-pinned to
    // the new checksum so later saves don't orphan it.
    try {
      const openFlags = await pool.query(
        `SELECT id, cue_index, target_text, suggestion FROM subtitle_quality_flags
         WHERE movie_id = $1 AND lang = $2 AND status = 'open'`,
        [movieId, lang]
      );
      const resolvedBy = req.user?.email || null;
      for (const flag of openFlags.rows) {
        const saved = clean[flag.cue_index];
        if (!saved) {
          await pool.query(
            `UPDATE subtitle_quality_flags SET status = 'stale' WHERE id = $1`,
            [flag.id]
          );
        } else if (saved.text === flag.target_text) {
          await pool.query(`UPDATE subtitle_quality_flags SET file_md5 = $2 WHERE id = $1`, [
            flag.id,
            fresh?.md5_checksum || null,
          ]);
        } else if (flag.suggestion && saved.text === flag.suggestion) {
          await pool.query(
            `UPDATE subtitle_quality_flags SET status = 'accepted',
               resolved_at = CURRENT_TIMESTAMP, resolved_by = $2 WHERE id = $1`,
            [flag.id, resolvedBy]
          );
        } else {
          await pool.query(
            `UPDATE subtitle_quality_flags SET status = 'stale' WHERE id = $1`,
            [flag.id]
          );
        }
      }
    } catch (flagError) {
      logError(flagError, req, { operation: 'reconcile_subtitle_quality_flags', movieId });
    }

    res.json({ file: fresh });
  } catch (error) {
    logError(error, req, { operation: 'save_subtitle_cues', movieId });
    if (!res.headersSent) res.status(500).json({ error: error.message });
  }
});

// POST /subtitles/:lang/use-synced — make the alass-synced copy the original:
// its cues overwrite the original file in place (same Drive id and name, so
// Drive's version history keeps the old timing), then the synced copy is
// trashed. Open flags on the synced copy move over to the original.
router.post('/subtitles/:lang/use-synced', async (req, res) => {
  const { movieId, lang } = req.params;
  if (!['cs', 'en'].includes(lang)) {
    return res.status(400).json({ error: 'Unsupported subtitle language' });
  }
  if (!googleDrive.isConfigured()) return notConfigured(res);
  try {
    const movie = await loadMovie(movieId);
    if (!movie) return res.status(404).json({ error: 'Movie not found' });

    const synced = await loadSubtitleRow(movieId, `${lang}_synced`);
    if (!synced) return res.status(404).json({ error: 'No synced subtitles to use' });

    const activeSync = await pool.query(
      `SELECT id FROM subtitle_sync_jobs
       WHERE movie_id = $1 AND subtitle_kind = $2 AND status IN ('pending', 'running')`,
      [movieId, `subtitles_${lang}`]
    );
    if (activeSync.rows.length > 0) {
      return res.status(409).json({ error: 'A sync job is still running for this track' });
    }

    const { text: syncedText } = await readRowText(synced);
    let cues;
    try {
      cues = parseSubtitles(syncedText, 'srt');
    } catch (parseError) {
      return res.status(422).json({ error: parseError.message });
    }

    const original = await loadSubtitleRow(movieId, lang);
    const kind = `subtitles_${lang}`;
    // Keep the original's format; a missing original becomes a fresh .srt.
    const ext = original && extensionOf(original.file_name) === 'vtt' ? 'vtt' : 'srt';
    const body = Buffer.from(ext === 'vtt' ? serializeVtt(cues) : serializeSrt(cues), 'utf8');

    let meta;
    if (original) {
      const { changed } = await checkDriveUnchanged(movieId, original, original.md5_checksum);
      if (changed) {
        return res.status(409).json({
          error:
            'The original subtitles were changed on Drive outside the app. ' +
            'Check them first; replacing again will overwrite that change.',
        });
      }
      meta = await googleDrive.updateFileContent({
        fileId: original.drive_file_id,
        mimeType: subtitleMime(ext),
        body,
      });
    } else {
      const folderId = await googleDrive.ensureMovieFolder(movie);
      meta = await googleDrive.uploadSmallFile({
        folderId,
        name: conventionFileName(movie, kind, ext),
        mimeType: subtitleMime(ext),
        body,
      });
    }
    await upsertFileRow(movieId, kind, meta);
    await cacheWritten(req, movieId, meta, body);

    await googleDrive.trashFile(synced.drive_file_id).catch((trashError) => {
      if (!isDriveNotFound(trashError)) {
        logError(trashError, req, { operation: 'trash_promoted_synced_subtitles', movieId });
      }
    });
    await pool.query('DELETE FROM movie_files WHERE movie_id = $1 AND file_kind = $2', [
      movieId,
      `${kind}_synced`,
    ]);

    // The original's findings described the old text; the synced copy's
    // findings still match cue-for-cue, so re-home them onto the original.
    await staleOpenFlags(req, movieId, lang);
    try {
      await pool.query(
        `UPDATE subtitle_quality_flags SET lang = $2, file_drive_id = $3, file_md5 = $4
         WHERE movie_id = $1 AND lang = $5 AND status = 'open'`,
        [movieId, lang, meta.id, meta.md5Checksum || null, `${lang}_synced`]
      );
    } catch (flagError) {
      logError(flagError, req, { operation: 'rehome_subtitle_quality_flags', movieId });
    }

    res.json({ file: await loadSubtitleRow(movieId, lang) });
  } catch (error) {
    if (error.statusCode === 413) {
      return res.status(413).json({ error: error.message });
    }
    logError(error, req, { operation: 'use_synced_subtitles', movieId });
    if (!res.headersSent) res.status(500).json({ error: error.message });
  }
});

// PUT /ready — set or clear the manual "files ready" mark ({ ready: bool }).
router.put('/ready', async (req, res) => {
  const { movieId } = req.params;
  try {
    const ready = req.body?.ready === true;
    const result = await pool.query(
      `UPDATE movies SET files_ready_at = $2, files_ready_by = $3
       WHERE id = $1 RETURNING files_ready_at, files_ready_by`,
      [movieId, ready ? new Date() : null, ready ? req.user?.email || null : null]
    );
    if (result.rows.length === 0) return res.status(404).json({ error: 'Movie not found' });
    res.json({ ready: readyOf(result.rows[0]) });
  } catch (error) {
    logError(error, req, { operation: 'set_movie_files_ready', movieId });
    res.status(500).json({ error: error.message });
  }
});

// DELETE /:fileKind — drop the pointer row and either trash the Drive file or
// rename it to {name}.removed.{ext}. The rename matters: the folder scan that
// runs on every page load would otherwise re-adopt the file by its convention
// name and the asset would come straight back.
router.delete('/:fileKind', async (req, res) => {
  const { movieId, fileKind } = req.params;
  const removeFromDrive = req.query.remove_from_drive === 'true';
  try {
    if (!FILE_KINDS.includes(fileKind)) {
      return res.status(400).json({ error: 'Invalid file kind' });
    }
    const existing = await pool.query(
      'SELECT * FROM movie_files WHERE movie_id = $1 AND file_kind = $2',
      [movieId, fileKind]
    );
    if (existing.rows.length === 0) {
      return res.status(404).json({ error: 'File not found' });
    }
    const row = existing.rows[0];

    let renamedTo = null;
    if (googleDrive.isConfigured()) {
      try {
        if (removeFromDrive) {
          await googleDrive.trashFile(row.drive_file_id);
        } else {
          const target = detachedFileName(row.file_name);
          if (target !== row.file_name) {
            await googleDrive.renameFile(row.drive_file_id, target);
            renamedTo = target;
          }
        }
      } catch (driveError) {
        // Already gone from Drive — removing the pointer is all that's left.
        if (!isDriveNotFound(driveError)) throw driveError;
      }
    } else if (removeFromDrive) {
      return notConfigured(res);
    }

    await pool.query(
      'DELETE FROM movie_files WHERE movie_id = $1 AND file_kind = $2',
      [movieId, fileKind]
    );
    if (fileKind.startsWith('subtitles_')) {
      await staleOpenFlags(req, movieId, fileKind.replace('subtitles_', ''));
    }
    res.json({ message: 'File removed', trashed: removeFromDrive, renamed_to: renamedTo });
  } catch (error) {
    logError(error, req, { operation: 'delete_movie_file', movieId });
    res.status(500).json({ error: error.message });
  }
});

module.exports = router;
