/**
 * Per-movie file management: /api/movies/:movieId/files
 *
 * Primary copies live in Azure Blob (see services/movieStorage.js); Google
 * Drive keeps the human-facing backup (masters, subtitle mirrors) and remains
 * the store for legacy rows of editions that never moved.
 *
 * Mounted with mergeParams so :movieId is available. Drive-dependent endpoints
 * return 503 when Google Drive is not configured; GET degrades to DB rows with
 * a drive_error flag so the UI always renders known status.
 */

const express = require('express');
const { pool } = require('../models/database');
const { logError } = require('../utils/logger');
const { logAuditEvent } = require('../utils/auditLogger');
const googleDrive = require('../services/googleDrive');
const movieStorage = require('../services/movieStorage');
const fileTransferQueue = require('../services/fileTransferQueue');
const { proxyDriveMedia } = require('../services/driveMediaProxy');
const transcodeQueue = require('../services/transcodeQueue');
const {
  convertSrtToVtt,
  parseSubtitles,
  serializeSrt,
  serializeVtt,
} = require('../utils/subtitles');
const { scanMovie, upsertFileRow } = require('../services/movieFileScanner');
const { cacheSubtitleTextSafe } = require('../services/subtitleCache');
const {
  conventionFileName,
  detachedFileName,
  extensionOf,
  isVideoFile,
  SUBTITLE_EXTENSIONS,
  FILE_KINDS,
} = require('../utils/movieFileNaming');

const router = express.Router({ mergeParams: true });

const { MAX_SUBTITLE_BYTES } = movieStorage;
const SUBTITLE_KINDS = ['subtitles_cs', 'subtitles_en'];
// Languages accepted by the /subtitles/:lang routes (subtitles_{lang} kinds).
// Synced variants are machine-generated by the sync worker but serve/edit the same way.
const SUBTITLE_LANGS = ['cs', 'en', 'cs_synced', 'en_synced'];
// File kinds that are playable video and can be streamed to the browser.
const STREAMABLE_KINDS = ['movie', 'movie_proxy'];

function notConfigured(res) {
  return res.status(503).json({ error: 'Google Drive is not configured' });
}

/** Drive "file not found" (already deleted/trashed elsewhere). */
function isDriveNotFound(error) {
  return error?.code === 404 || error?.response?.status === 404;
}

/** The manual "files ready" mark from a loadMovie() row, or null. */
function readyOf(movie) {
  return movie.files_ready_at
    ? { at: movie.files_ready_at, by: movie.files_ready_by || null }
    : null;
}

/**
 * Ensure a file's type matches the kind slot it will occupy:
 * subtitle kinds require .srt/.vtt; the movie kind requires a video file.
 * Returns an error string, or null if valid.
 */
function validateKindForFile(fileKind, fileName, mimeType) {
  const ext = extensionOf(fileName);
  if (
    (SUBTITLE_KINDS.includes(fileKind) || fileKind.endsWith('_synced')) &&
    !SUBTITLE_EXTENSIONS.includes(ext)
  ) {
    return 'Subtitles must be .srt or .vtt';
  }
  if (fileKind === 'movie' && !isVideoFile(fileName, mimeType)) {
    return 'Movie asset must be a video file';
  }
  if (fileKind === 'movie_proxy' && ext !== 'mp4') {
    return 'Preview proxy must be an .mp4';
  }
  return null;
}

/** Load a movie row with edition_year, or null. */
async function loadMovie(movieId) {
  const res = await pool.query(
    `SELECT m.id, m.name_cs, m.name_en, m.drive_folder_id, m.files_ready_at,
            m.files_ready_by, e.year AS edition_year
     FROM movies m JOIN editions e ON m.edition_id = e.id
     WHERE m.id = $1`,
    [movieId]
  );
  return res.rows[0] || null;
}

/** Subtitle format of a row's primary copy. */
function rowExt(row) {
  return extensionOf(row.storage === 'azure' ? row.blob_name : row.file_name);
}

/**
 * Write subtitles through movieStorage (Azure + Drive mirror, or legacy
 * Drive) and keep the subtitle cache warm for Drive-stored results.
 */
async function writeSubtitles(req, movie, fileKind, body, { ext, ifMatch } = {}) {
  const fresh = await movieStorage.writeSubtitleFile(movie, fileKind, body, {
    ext,
    ifMatch,
    onMirrorError: (mirrorError) =>
      logError(mirrorError, req, { operation: 'mirror_subtitles_to_drive', movieId: movie.id }),
  });
  if (fresh.storage === 'drive') {
    await cacheSubtitleTextSafe(
      fresh.drive_file_id,
      { bytes: body, md5: fresh.md5_checksum || null },
      (cacheError) => logError(cacheError, req, { operation: 'cache_subtitle_text', movieId: movie.id })
    );
  }
  return fresh;
}

/**
 * Has the file been changed behind the app's back since `baseMd5`?
 *   Azure rows: the blob's md5 (concurrent edit in the app) and the Drive
 *     mirror's md5 vs the last one the app wrote (edit on Drive), unless
 *     overwriteDrive.
 *   Drive rows: the Drive file's md5; on a mismatch the pointer row is
 *     refreshed so the next read re-downloads instead of serving cached text.
 * @returns {Promise<{conflict: null|{code: string, error: string}, etag?: string}>}
 */
async function checkUnchanged(movieId, row, baseMd5, { overwriteDrive = false } = {}) {
  if (row.storage === 'azure') {
    const props = await movieStorage.getProperties(row.blob_name);
    const blobMd5 = movieStorage.base64ToHex(props.contentMD5);
    if (baseMd5 && blobMd5 && blobMd5 !== baseMd5) {
      return {
        conflict: {
          code: 'changed',
          error:
            'Subtitles were changed in the app since you loaded them. ' +
            'Reload to get the current version (your unsaved edits will be lost).',
        },
      };
    }
    if (row.drive_file_id && !overwriteDrive) {
      const meta = await googleDrive.getFileMetadata(row.drive_file_id).catch((e) => {
        if (isDriveNotFound(e)) return null;
        throw e;
      });
      if (meta?.md5Checksum && row.drive_md5_checksum && meta.md5Checksum !== row.drive_md5_checksum) {
        return {
          conflict: {
            code: 'drive_changed',
            error:
              'The Drive copy of these subtitles was edited outside the app. ' +
              'Use the Drive version, or overwrite it with yours.',
          },
        };
      }
    }
    return { conflict: null, etag: props.etag };
  }

  const meta = await googleDrive.getFileMetadata(row.drive_file_id);
  if (meta.md5Checksum && baseMd5 && meta.md5Checksum !== baseMd5) {
    await upsertFileRow(movieId, row.file_kind, meta);
    return {
      conflict: {
        code: 'changed',
        error:
          'Subtitles were changed on Drive outside the app since you loaded them. ' +
          'Reload the editor to get the current version (your unsaved edits will be lost).',
      },
    };
  }
  return { conflict: null };
}

/**
 * Mark a subtitle track's open quality flags stale (its file was replaced or
 * removed, so the findings no longer describe it). Non-fatal.
 */
async function staleOpenFlags(req, movieId, lang) {
  try {
    await pool.query(
      `UPDATE subtitle_quality_flags SET status = 'stale'
       WHERE movie_id = $1 AND lang = $2 AND status = 'open'`,
      [movieId, lang]
    );
  } catch (flagError) {
    logError(flagError, req, { operation: 'stale_subtitle_quality_flags', movieId });
  }
}

/** The audit-relevant fields of a movie_files row, or null. */
function auditSnapshot(row) {
  if (!row) return null;
  return {
    file_kind: row.file_kind,
    file_name: row.file_name,
    file_size: row.file_size,
    storage: row.storage,
    md5_checksum: row.md5_checksum,
  };
}

/**
 * Record a file change in the audit log (resource movie_files, id = the
 * movie). Action is CREATE when the slot was empty, else UPDATE, unless given.
 */
function auditFileChange(req, operation, { before = null, after = null, action, extra = {} } = {}) {
  return logAuditEvent({
    req,
    action: action || (before ? 'UPDATE' : 'CREATE'),
    resource: 'movie_files',
    resourceId: req.params.movieId,
    oldData: auditSnapshot(before),
    newData: (after || Object.keys(extra).length) ? { ...auditSnapshot(after), ...extra } : null,
    additionalMetadata: { operation },
  });
}

/** Load the movie_files row for a subtitle language, or null. */
async function loadSubtitleRow(movieId, lang) {
  return movieStorage.loadRow(movieId, `subtitles_${lang}`);
}

/**
 * Remove a row's Drive copy: trash it, or rename it to {name}.removed.{ext}
 * so the folder scan doesn't re-adopt it. Missing files are fine.
 */
async function detachDriveCopy(driveFileId, { trash }) {
  if (!driveFileId) return null;
  try {
    if (trash) {
      await googleDrive.trashFile(driveFileId);
      return null;
    }
    const meta = await googleDrive.getFileMetadata(driveFileId);
    const target = detachedFileName(meta.name);
    if (target !== meta.name) await googleDrive.renameFile(driveFileId, target);
    return target;
  } catch (driveError) {
    if (isDriveNotFound(driveError)) return null;
    throw driveError;
  }
}

// GET / — DB rows always; live folder listing + unclassified when Drive is up.
router.get('/', async (req, res) => {
  const { movieId } = req.params;
  try {
    const movie = await loadMovie(movieId);
    if (!movie) return res.status(404).json({ error: 'Movie not found' });
    const common = {
      ready: readyOf(movie),
      azure_configured: movieStorage.isConfigured(),
    };

    if (!googleDrive.isConfigured()) {
      const dbRows = await pool.query(
        'SELECT * FROM movie_files WHERE movie_id = $1 ORDER BY file_kind',
        [movieId]
      );
      return res.json({
        files: dbRows.rows,
        folder: movie.drive_folder_id ? { id: movie.drive_folder_id } : null,
        unclassified: [],
        drive_configured: false,
        ...common,
      });
    }

    // Live scan reconciles rows and surfaces unclassified files.
    try {
      const result = await scanMovie(movieId);
      return res.json({ ...result, drive_configured: true, ...common });
    } catch (driveError) {
      logError(driveError, req, { operation: 'movie_files_scan', movieId });
      const dbRows = await pool.query(
        'SELECT * FROM movie_files WHERE movie_id = $1 ORDER BY file_kind',
        [movieId]
      );
      return res.json({
        files: dbRows.rows,
        folder: movie.drive_folder_id ? { id: movie.drive_folder_id } : null,
        unclassified: [],
        drive_configured: true,
        drive_error: driveError.message,
        ...common,
      });
    }
  } catch (error) {
    logError(error, req, { operation: 'get_movie_files', movieId });
    res.status(500).json({ error: error.message });
  }
});

// POST /folder — ensure the Drive folder exists for this movie.
router.post('/folder', async (req, res) => {
  const { movieId } = req.params;
  if (!googleDrive.isConfigured()) return notConfigured(res);
  try {
    const movie = await loadMovie(movieId);
    if (!movie) return res.status(404).json({ error: 'Movie not found' });
    const folderId = await googleDrive.ensureMovieFolder(movie);
    res.json({ folder: { id: folderId } });
  } catch (error) {
    logError(error, req, { operation: 'ensure_movie_folder', movieId });
    res.status(500).json({ error: error.message });
  }
});

// POST /rescan — reconcile rows against Drive on demand.
router.post('/rescan', async (req, res) => {
  const { movieId } = req.params;
  if (!googleDrive.isConfigured()) return notConfigured(res);
  try {
    const result = await scanMovie(movieId);
    res.json({ ...result, drive_configured: true });
  } catch (error) {
    logError(error, req, { operation: 'rescan_movie_files', movieId });
    res.status(error.statusCode || 500).json({ error: error.message });
  }
});

// POST /upload-session — where the browser uploads a big file: a blob SAS URL
// (Azure) or a Drive resumable session (legacy editions).
router.post('/upload-session', async (req, res) => {
  const { movieId } = req.params;
  if (!googleDrive.isConfigured()) return notConfigured(res);
  try {
    const { file_kind, file_name, file_size, mime_type } = req.body;
    if (!FILE_KINDS.includes(file_kind)) {
      return res.status(400).json({ error: 'Invalid file_kind' });
    }
    const kindError = validateKindForFile(file_kind, file_name, mime_type);
    if (kindError) return res.status(400).json({ error: kindError });

    const movie = await loadMovie(movieId);
    if (!movie) return res.status(404).json({ error: 'Movie not found' });

    const ext = extensionOf(file_name) || 'bin';
    const existing = await movieStorage.loadRow(movieId, file_kind);
    if (movieStorage.targetStorage(movie, existing) === 'azure') {
      const blobName = movieStorage.blobNameFor(movie, file_kind, ext);
      return res.json({
        target: 'azure',
        upload_url: await movieStorage.uploadUrl(blobName),
        blob_name: blobName,
        tier: movieStorage.tierFor(file_kind),
        content_type: mime_type || 'application/octet-stream',
      });
    }

    const folderId = await googleDrive.ensureMovieFolder(movie);
    const targetName = conventionFileName(movie, file_kind, ext);
    const origin = req.get('origin') || process.env.APP_URL;
    const uploadUrl = await googleDrive.createResumableSession({
      folderId,
      name: targetName,
      mimeType: mime_type,
      size: file_size,
      origin,
    });
    res.json({ target: 'drive', upload_url: uploadUrl, target_name: targetName });
  } catch (error) {
    logError(error, req, { operation: 'create_upload_session', movieId });
    res.status(500).json({ error: error.message });
  }
});

// POST /upload-complete — verify the uploaded file and record the row.
// Azure: { file_kind, blob_name }; Drive: { file_kind, drive_file_id }.
router.post('/upload-complete', async (req, res) => {
  const { movieId } = req.params;
  if (!googleDrive.isConfigured()) return notConfigured(res);
  try {
    const { file_kind, drive_file_id, blob_name } = req.body;
    if (!FILE_KINDS.includes(file_kind)) {
      return res.status(400).json({ error: 'Invalid file_kind' });
    }
    if (!drive_file_id && !blob_name) {
      return res.status(400).json({ error: 'drive_file_id or blob_name is required' });
    }
    const movie = await loadMovie(movieId);
    if (!movie) return res.status(404).json({ error: 'Movie not found' });

    if (blob_name) {
      if (!movieStorage.isConfigured() || !movieStorage.blobBelongsTo(movie, blob_name)) {
        return res.status(400).json({ error: 'Blob does not belong to this movie' });
      }
      const taken = await pool.query('SELECT file_kind FROM movie_files WHERE blob_name = $1', [blob_name]);
      if (taken.rows.length > 0) {
        return res.status(409).json({ error: 'This upload is already recorded' });
      }
      const props = await movieStorage.getProperties(blob_name).catch(() => null);
      if (!props) return res.status(400).json({ error: 'Uploaded file not found' });
      const fileName = movieStorage.displayName(blob_name);
      const kindError = validateKindForFile(file_kind, fileName, props.contentType);
      if (kindError) {
        await movieStorage.deleteBlob(blob_name).catch(() => {});
        return res.status(400).json({ error: kindError });
      }

      const existing = await movieStorage.loadRow(movieId, file_kind);
      // The Drive pointer still names the previous version's backup; the
      // backup job below replaces (and trashes) it.
      await movieStorage.upsertAzureRow(movieId, file_kind, {
        blobName: blob_name,
        fileName,
        size: props.contentLength,
        mimeType: props.contentType,
        md5: movieStorage.base64ToHex(props.contentMD5),
        etag: props.etag,
      });
      if (existing?.storage === 'azure' && existing.blob_name !== blob_name) {
        await movieStorage.deleteBlob(existing.blob_name).catch((e) =>
          logError(e, req, { operation: 'delete_replaced_blob', movieId })
        );
      }
      const fresh = await movieStorage.loadRow(movieId, file_kind);
      await auditFileChange(req, 'upload', { before: existing, after: fresh });
      if (file_kind === 'movie') {
        // Awaited so the job rows exist before we respond (the client reloads
        // the player right after and needs to see them to start polling).
        await transcodeQueue.enqueueForMovie(movieId, req.user?.email);
        await fileTransferQueue.enqueueBackup(fresh, { createdBy: req.user?.email });
      }
      return res.json({ file: fresh });
    }

    if (!movie.drive_folder_id) {
      return res.status(400).json({ error: 'Movie has no Drive folder' });
    }
    const meta = await googleDrive.getFileMetadata(drive_file_id);
    // Only record files that actually live in this movie's folder.
    if (!meta.parents || !meta.parents.includes(movie.drive_folder_id)) {
      return res.status(400).json({ error: 'File is not in this movie folder' });
    }
    const kindError = validateKindForFile(file_kind, meta.name, meta.mimeType);
    if (kindError) return res.status(400).json({ error: kindError });

    const prior = await movieStorage.loadRow(movieId, file_kind);
    await upsertFileRow(movieId, file_kind, meta);
    const fresh = await movieStorage.loadRow(movieId, file_kind);
    await auditFileChange(req, 'upload', { before: prior, after: fresh });
    if (file_kind === 'movie') {
      await transcodeQueue.enqueueForMovie(movieId, req.user?.email);
    }
    res.json({ file: fresh });
  } catch (error) {
    logError(error, req, { operation: 'upload_complete', movieId });
    res.status(500).json({ error: error.message });
  }
});

// POST /subtitles — small subtitle upload through the backend (base64).
router.post('/subtitles', async (req, res) => {
  const { movieId } = req.params;
  if (!googleDrive.isConfigured()) return notConfigured(res);
  try {
    const { file_kind, file_name, content_base64 } = req.body;
    if (!SUBTITLE_KINDS.includes(file_kind)) {
      return res.status(400).json({ error: 'file_kind must be a subtitle kind' });
    }
    const ext = extensionOf(file_name);
    if (!SUBTITLE_EXTENSIONS.includes(ext)) {
      return res.status(400).json({ error: 'Subtitles must be .srt or .vtt' });
    }
    if (!content_base64) {
      return res.status(400).json({ error: 'content_base64 is required' });
    }
    const body = Buffer.from(content_base64, 'base64');
    if (body.length > MAX_SUBTITLE_BYTES) {
      return res.status(413).json({ error: 'Subtitles file is too large' });
    }

    const movie = await loadMovie(movieId);
    if (!movie) return res.status(404).json({ error: 'Movie not found' });

    const prior = await movieStorage.loadRow(movieId, file_kind);
    const fresh = await writeSubtitles(req, movie, file_kind, body, { ext });
    await auditFileChange(req, 'upload_subtitles', {
      before: prior,
      after: fresh,
      extra: { uploaded_name: file_name },
    });
    if (prior) await staleOpenFlags(req, movieId, file_kind.replace('subtitles_', ''));
    res.json({ file: fresh });
  } catch (error) {
    logError(error, req, { operation: 'upload_subtitles', movieId });
    res.status(500).json({ error: error.message });
  }
});

// POST /import — classify a file already sitting in the movie's Drive folder.
// Editions in Azure: subtitles are copied into Azure right away (the Drive
// file becomes their mirror); videos are copied by a background transfer job
// that updates the row when done.
router.post('/import', async (req, res) => {
  const { movieId } = req.params;
  if (!googleDrive.isConfigured()) return notConfigured(res);
  try {
    const { drive_file_id, file_kind, rename, replace } = req.body;
    if (!FILE_KINDS.includes(file_kind)) {
      return res.status(400).json({ error: 'Invalid file_kind' });
    }
    if (!drive_file_id) {
      return res.status(400).json({ error: 'drive_file_id is required' });
    }
    const movie = await loadMovie(movieId);
    if (!movie) return res.status(404).json({ error: 'Movie not found' });
    if (!movie.drive_folder_id) {
      return res.status(400).json({ error: 'Movie has no Drive folder' });
    }

    let meta = await googleDrive.getFileMetadata(drive_file_id);
    if (!meta.parents || !meta.parents.includes(movie.drive_folder_id)) {
      return res.status(400).json({ error: 'File is not in this movie folder' });
    }
    const kindError = validateKindForFile(file_kind, meta.name, meta.mimeType);
    if (kindError) return res.status(400).json({ error: kindError });

    // 409 if the kind is already occupied, unless replace is requested.
    const existing = await movieStorage.loadRow(movieId, file_kind);
    if (existing && existing.drive_file_id !== drive_file_id && !replace) {
      return res.status(409).json({ error: 'This asset kind is already set' });
    }

    if (rename) {
      const ext = extensionOf(meta.name) || 'bin';
      const targetName = conventionFileName(movie, file_kind, ext);
      if (targetName !== meta.name) {
        await googleDrive.renameFile(drive_file_id, targetName);
        meta = await googleDrive.getFileMetadata(drive_file_id);
      }
    }

    if (movieStorage.targetStorage(movie, existing) === 'azure') {
      if (file_kind.startsWith('subtitles_')) {
        const body = await movieStorage.readBuffer(drive_file_id);
        const ext = extensionOf(meta.name);
        const blobName = movieStorage.blobNameFor(movie, file_kind, ext);
        const written = await movieStorage.uploadBuffer(blobName, body, {
          fileKind: file_kind,
          contentType: `${movieStorage.subtitleMime(ext)}; charset=utf-8`,
        });
        await movieStorage.upsertAzureRow(movieId, file_kind, {
          blobName,
          fileName: conventionFileName(movie, file_kind, ext),
          size: written.size,
          mimeType: movieStorage.subtitleMime(ext),
          md5: written.md5,
          etag: written.etag,
          drive: { id: drive_file_id, md5: meta.md5Checksum || written.md5 },
        });
        if (existing?.storage === 'azure') {
          await movieStorage.deleteBlob(existing.blob_name).catch(() => {});
        }
        if (existing?.drive_file_id && existing.drive_file_id !== drive_file_id) {
          await googleDrive.trashFile(existing.drive_file_id).catch(() => {});
        }
        if (existing) await staleOpenFlags(req, movieId, file_kind.replace('subtitles_', ''));
        const fresh = await movieStorage.loadRow(movieId, file_kind);
        await auditFileChange(req, 'import', { before: existing, after: fresh });
        return res.json({ file: fresh });
      }

      if (!fileTransferQueue.isConfigured()) {
        return res.status(503).json({ error: 'Copying into Azure is not configured' });
      }
      const job = await fileTransferQueue.enqueue({
        movieId,
        fileKind: file_kind,
        direction: 'drive_to_azure',
        sourceRef: drive_file_id,
        transcodeAfter: file_kind === 'movie',
        // A person picked this file for the slot: it wins over the current one.
        replaceExisting: true,
        createdBy: req.user?.email,
      });
      if (!job) {
        return res.status(409).json({ error: 'A copy of this asset into Azure is already running' });
      }
      // The row changes when the transfer finishes; log the request now.
      await auditFileChange(req, 'import', {
        before: existing,
        extra: { file_kind, drive_file_id, drive_file_name: meta.name, transfer_job_id: job.id },
      });
      return res.status(202).json({ transfer: job, file: existing });
    }

    await upsertFileRow(movieId, file_kind, meta);
    const fresh = await movieStorage.loadRow(movieId, file_kind);
    await auditFileChange(req, 'import', { before: existing, after: fresh });
    // Importing a master as the movie kicks off proxy generation. Awaited so the
    // job row exists before we respond (the client reloads the player right after
    // and needs to see the pending job to start polling).
    if (file_kind === 'movie') {
      await transcodeQueue.enqueueForMovie(movieId, req.user?.email);
    }
    res.json({ file: fresh });
  } catch (error) {
    logError(error, req, { operation: 'import_movie_file', movieId });
    res.status(500).json({ error: error.message });
  }
});

// GET /stream/:fileKind — video bytes for the player: a redirect to a
// short-lived read URL (Azure, Range handled by Blob Storage) or a proxied
// Drive stream (legacy).
router.get('/stream/:fileKind', async (req, res) => {
  const { movieId, fileKind } = req.params;
  if (!STREAMABLE_KINDS.includes(fileKind)) {
    return res.status(400).json({ error: 'Not a streamable file kind' });
  }
  try {
    const row = await movieStorage.loadRow(movieId, fileKind);
    if (!row) return res.status(404).json({ error: 'File not found' });
    if (row.storage === 'azure') {
      res.setHeader('Cache-Control', 'private, no-store');
      return res.redirect(302, await movieStorage.readUrl(row.blob_name));
    }
    if (!googleDrive.isConfigured()) return notConfigured(res);
    await proxyDriveMedia(req, res, row.drive_file_id, row.mime_type || 'video/mp4');
  } catch (error) {
    logError(error, req, { operation: 'stream_movie_file', movieId });
    if (!res.headersSent) res.status(500).json({ error: error.message });
  }
});

// GET /download/:fileKind — save a file: a read URL with an attachment
// disposition (Azure) or the Drive file page (legacy).
router.get('/download/:fileKind', async (req, res) => {
  const { movieId, fileKind } = req.params;
  if (!FILE_KINDS.includes(fileKind)) {
    return res.status(400).json({ error: 'Invalid file kind' });
  }
  try {
    const row = await movieStorage.loadRow(movieId, fileKind);
    if (!row) return res.status(404).json({ error: 'File not found' });
    res.setHeader('Cache-Control', 'private, no-store');
    if (row.storage === 'azure') {
      return res.redirect(
        302,
        await movieStorage.readUrl(row.blob_name, { downloadName: row.file_name })
      );
    }
    res.redirect(302, `https://drive.google.com/file/d/${encodeURIComponent(row.drive_file_id)}/view`);
  } catch (error) {
    logError(error, req, { operation: 'download_movie_file', movieId });
    if (!res.headersSent) res.status(500).json({ error: error.message });
  }
});

// GET /subtitles/:lang — serve the subtitle as VTT (player tracks).
router.get('/subtitles/:lang', async (req, res) => {
  const { movieId, lang } = req.params;
  const cleanLang = String(lang).replace(/\.vtt$/i, '');
  if (!SUBTITLE_LANGS.includes(cleanLang)) {
    return res.status(400).json({ error: 'Unsupported subtitle language' });
  }
  try {
    const row = await loadSubtitleRow(movieId, cleanLang);
    if (!row) return res.status(404).json({ error: 'Subtitles not found' });
    if (row.storage === 'drive' && !googleDrive.isConfigured()) return notConfigured(res);

    const { text } = await movieStorage.readSubtitleRow(row);
    const vtt = rowExt(row) === 'vtt' ? text : convertSrtToVtt(text);

    res.setHeader('Content-Type', 'text/vtt; charset=utf-8');
    res.send(vtt);
  } catch (error) {
    if (error.statusCode === 413) {
      return res.status(413).json({ error: error.message });
    }
    logError(error, req, { operation: 'get_subtitles', movieId });
    if (!res.headersSent) res.status(500).json({ error: error.message });
  }
});

// GET /subtitles/:lang/cues — parsed subtitle cues as JSON, for the editor.
router.get('/subtitles/:lang/cues', async (req, res) => {
  const { movieId, lang } = req.params;
  if (!SUBTITLE_LANGS.includes(lang)) {
    return res.status(400).json({ error: 'Unsupported subtitle language' });
  }
  try {
    const row = await loadSubtitleRow(movieId, lang);
    if (!row) return res.status(404).json({ error: 'Subtitles not found' });
    if (row.storage === 'drive' && !googleDrive.isConfigured()) return notConfigured(res);

    const ext = rowExt(row);
    const { text, md5, source, driveError } = await movieStorage.readSubtitleRow(row);
    let cues;
    try {
      cues = parseSubtitles(text, ext);
    } catch (parseError) {
      return res.status(422).json({ error: parseError.message });
    }

    res.json({
      file: {
        file_name: row.file_name,
        storage: row.storage,
        // The md5 of the text actually returned — the editor saves against it.
        md5_checksum: md5,
        drive_modified_at: row.drive_modified_at,
      },
      format: ext === 'vtt' ? 'vtt' : 'srt',
      cues,
      // 'stale-cache': Drive refused the download, this is the last cached copy.
      cache: { source, drive_error: driveError || null },
    });
  } catch (error) {
    if (error.statusCode === 413) {
      return res.status(413).json({ error: error.message });
    }
    logError(error, req, { operation: 'get_subtitle_cues', movieId });
    if (!res.headersSent) res.status(500).json({ error: error.message });
  }
});

// Timing lines are copied verbatim from the parsed source, so accept the SRT
// form with optional trailing cue settings/coordinates.
const CUE_TIMING_RE =
  /^\d{1,2}:\d{2}:\d{2}[,.]\d{1,3}\s+-->\s+\d{1,2}:\d{2}:\d{2}[,.]\d{1,3}(\s.*)?$/;

// PUT /subtitles/:lang/cues — save edited cue texts (timings never change).
// Body: { cues, base_md5, overwrite_drive? }. 409 with code 'changed' (the
// file moved on since it was loaded) or 'drive_changed' (the Drive copy was
// edited outside the app; resend with overwrite_drive to replace it).
router.put('/subtitles/:lang/cues', async (req, res) => {
  const { movieId, lang } = req.params;
  if (!SUBTITLE_LANGS.includes(lang)) {
    return res.status(400).json({ error: 'Unsupported subtitle language' });
  }
  if (!googleDrive.isConfigured()) return notConfigured(res);
  try {
    const { cues, base_md5, overwrite_drive } = req.body || {};
    if (!Array.isArray(cues) || cues.length === 0) {
      return res.status(400).json({ error: 'cues must be a non-empty array' });
    }
    if (!base_md5) {
      return res.status(400).json({ error: 'base_md5 is required' });
    }
    for (const cue of cues) {
      if (
        !cue ||
        typeof cue.timing !== 'string' ||
        !CUE_TIMING_RE.test(cue.timing.trim()) ||
        typeof cue.text !== 'string'
      ) {
        return res
          .status(400)
          .json({ error: 'Each cue needs a valid timing line and a text string' });
      }
    }

    const movie = await loadMovie(movieId);
    if (!movie) return res.status(404).json({ error: 'Movie not found' });
    const row = await loadSubtitleRow(movieId, lang);
    if (!row) return res.status(404).json({ error: 'Subtitles not found' });

    const { conflict, etag } = await checkUnchanged(movieId, row, base_md5, {
      overwriteDrive: overwrite_drive === true,
    });
    if (conflict) return res.status(409).json(conflict);

    const ext = rowExt(row);
    const clean = cues.map((c) => ({ timing: c.timing.trim(), text: c.text }));
    const text = ext === 'vtt' ? serializeVtt(clean) : serializeSrt(clean);
    const body = Buffer.from(text, 'utf8');
    if (body.length > MAX_SUBTITLE_BYTES) {
      return res.status(413).json({ error: 'Subtitles file is too large' });
    }

    let fresh;
    try {
      fresh = await writeSubtitles(req, movie, row.file_kind, body, { ext, ifMatch: etag });
    } catch (writeError) {
      // The blob changed between the check and the write (ETag mismatch).
      if (writeError.statusCode === 412) {
        return res.status(409).json({
          code: 'changed',
          error: 'Subtitles were changed in the app while saving. Reload to get the current version.',
        });
      }
      throw writeError;
    }
    await auditFileChange(req, 'edit_subtitles', {
      before: row,
      after: fresh,
      extra: { cue_count: clean.length, overwrite_drive: overwrite_drive === true },
    });

    // Reconcile open quality flags against the saved text (non-fatal):
    // suggestion applied -> accepted; text changed some other way (or the
    // file shape changed) -> stale; untouched -> stays open, re-pinned to
    // the new checksum so later saves don't orphan it.
    try {
      const openFlags = await pool.query(
        `SELECT id, cue_index, target_text, suggestion FROM subtitle_quality_flags
         WHERE movie_id = $1 AND lang = $2 AND status = 'open'`,
        [movieId, lang]
      );
      const resolvedBy = req.user?.email || null;
      for (const flag of openFlags.rows) {
        const saved = clean[flag.cue_index];
        if (!saved) {
          await pool.query(
            `UPDATE subtitle_quality_flags SET status = 'stale' WHERE id = $1`,
            [flag.id]
          );
        } else if (saved.text === flag.target_text) {
          await pool.query(
            `UPDATE subtitle_quality_flags SET file_md5 = $2, file_drive_id = $3 WHERE id = $1`,
            [flag.id, fresh?.md5_checksum || null, movieStorage.fileRef(fresh)]
          );
        } else if (flag.suggestion && saved.text === flag.suggestion) {
          await pool.query(
            `UPDATE subtitle_quality_flags SET status = 'accepted',
               resolved_at = CURRENT_TIMESTAMP, resolved_by = $2 WHERE id = $1`,
            [flag.id, resolvedBy]
          );
        } else {
          await pool.query(
            `UPDATE subtitle_quality_flags SET status = 'stale' WHERE id = $1`,
            [flag.id]
          );
        }
      }
    } catch (flagError) {
      logError(flagError, req, { operation: 'reconcile_subtitle_quality_flags', movieId });
    }

    res.json({ file: fresh });
  } catch (error) {
    logError(error, req, { operation: 'save_subtitle_cues', movieId });
    if (!res.headersSent) res.status(500).json({ error: error.message });
  }
});

// POST /subtitles/:lang/adopt-drive — the Drive copy of an Azure subtitle file
// was edited outside the app: make that version the app's version.
router.post('/subtitles/:lang/adopt-drive', async (req, res) => {
  const { movieId, lang } = req.params;
  if (!SUBTITLE_LANGS.includes(lang)) {
    return res.status(400).json({ error: 'Unsupported subtitle language' });
  }
  if (!googleDrive.isConfigured()) return notConfigured(res);
  try {
    const movie = await loadMovie(movieId);
    if (!movie) return res.status(404).json({ error: 'Movie not found' });
    const row = await loadSubtitleRow(movieId, lang);
    if (!row || row.storage !== 'azure' || !row.drive_file_id) {
      return res.status(404).json({ error: 'These subtitles have no Drive copy to use' });
    }
    const meta = await googleDrive.getFileMetadata(row.drive_file_id);
    const body = await movieStorage.readBuffer(row.drive_file_id);
    const ext = extensionOf(meta.name) === 'vtt' ? 'vtt' : 'srt';
    try {
      parseSubtitles(body.toString('utf8'), ext);
    } catch (parseError) {
      return res.status(422).json({ error: `The Drive copy is not valid subtitles: ${parseError.message}` });
    }
    const sameFormat = rowExt(row) === ext;
    const blobName = sameFormat ? row.blob_name : movieStorage.blobNameFor(movie, row.file_kind, ext);
    const written = await movieStorage.uploadBuffer(blobName, body, {
      fileKind: row.file_kind,
      contentType: `${movieStorage.subtitleMime(ext)}; charset=utf-8`,
    });
    await movieStorage.upsertAzureRow(movieId, row.file_kind, {
      blobName,
      fileName: conventionFileName(movie, row.file_kind, ext),
      size: written.size,
      mimeType: movieStorage.subtitleMime(ext),
      md5: written.md5,
      etag: written.etag,
      drive: { id: row.drive_file_id, md5: meta.md5Checksum || written.md5 },
    });
    if (!sameFormat) await movieStorage.deleteBlob(row.blob_name).catch(() => {});
    await staleOpenFlags(req, movieId, lang);
    const fresh = await loadSubtitleRow(movieId, lang);
    await auditFileChange(req, 'adopt_drive_subtitles', { before: row, after: fresh });
    res.json({ file: fresh });
  } catch (error) {
    if (error.statusCode === 413) {
      return res.status(413).json({ error: error.message });
    }
    logError(error, req, { operation: 'adopt_drive_subtitles', movieId });
    if (!res.headersSent) res.status(500).json({ error: error.message });
  }
});

// POST /subtitles/:lang/use-synced — make the alass-synced copy the original:
// its cues overwrite the original in place, then the synced copy is removed.
// Open flags on the synced copy move over to the original. Body:
// { overwrite_drive? } — see PUT /cues for the 409 codes.
router.post('/subtitles/:lang/use-synced', async (req, res) => {
  const { movieId, lang } = req.params;
  if (!['cs', 'en'].includes(lang)) {
    return res.status(400).json({ error: 'Unsupported subtitle language' });
  }
  if (!googleDrive.isConfigured()) return notConfigured(res);
  try {
    const movie = await loadMovie(movieId);
    if (!movie) return res.status(404).json({ error: 'Movie not found' });

    const synced = await loadSubtitleRow(movieId, `${lang}_synced`);
    if (!synced) return res.status(404).json({ error: 'No synced subtitles to use' });

    const activeSync = await pool.query(
      `SELECT id FROM subtitle_sync_jobs
       WHERE movie_id = $1 AND subtitle_kind = $2 AND status IN ('pending', 'running')`,
      [movieId, `subtitles_${lang}`]
    );
    if (activeSync.rows.length > 0) {
      return res.status(409).json({ error: 'A sync job is still running for this track' });
    }

    const { text: syncedText } = await movieStorage.readSubtitleRow(synced);
    let cues;
    try {
      cues = parseSubtitles(syncedText, 'srt');
    } catch (parseError) {
      return res.status(422).json({ error: parseError.message });
    }

    const original = await loadSubtitleRow(movieId, lang);
    const kind = `subtitles_${lang}`;
    // Keep the original's format; a missing original becomes a fresh .srt.
    const ext = original && rowExt(original) === 'vtt' ? 'vtt' : 'srt';
    const body = Buffer.from(ext === 'vtt' ? serializeVtt(cues) : serializeSrt(cues), 'utf8');

    let etag;
    if (original) {
      const check = await checkUnchanged(movieId, original, original.md5_checksum, {
        overwriteDrive: req.body?.overwrite_drive === true,
      });
      if (check.conflict) return res.status(409).json(check.conflict);
      etag = check.etag;
    }
    const fresh = await writeSubtitles(req, movie, kind, body, { ext, ifMatch: etag });
    await auditFileChange(req, 'use_synced_subtitles', {
      before: original,
      after: fresh,
      extra: { replaced_by: synced.file_name },
    });

    // Remove the synced copy (blob + Drive mirror, or the legacy Drive file).
    if (synced.storage === 'azure') {
      await movieStorage.deleteBlob(synced.blob_name).catch(() => {});
    }
    if (synced.drive_file_id) {
      await googleDrive.trashFile(synced.drive_file_id).catch((trashError) => {
        if (!isDriveNotFound(trashError)) {
          logError(trashError, req, { operation: 'trash_promoted_synced_subtitles', movieId });
        }
      });
    }
    await pool.query('DELETE FROM movie_files WHERE movie_id = $1 AND file_kind = $2', [
      movieId,
      `${kind}_synced`,
    ]);

    // The original's findings described the old text; the synced copy's
    // findings still match cue-for-cue, so re-home them onto the original.
    await staleOpenFlags(req, movieId, lang);
    try {
      await pool.query(
        `UPDATE subtitle_quality_flags SET lang = $2, file_drive_id = $3, file_md5 = $4
         WHERE movie_id = $1 AND lang = $5 AND status = 'open'`,
        [movieId, lang, movieStorage.fileRef(fresh), fresh.md5_checksum || null, `${lang}_synced`]
      );
    } catch (flagError) {
      logError(flagError, req, { operation: 'rehome_subtitle_quality_flags', movieId });
    }

    res.json({ file: await loadSubtitleRow(movieId, lang) });
  } catch (error) {
    if (error.statusCode === 413) {
      return res.status(413).json({ error: error.message });
    }
    if (error.statusCode === 412) {
      return res.status(409).json({ code: 'changed', error: 'The original subtitles changed while replacing. Try again.' });
    }
    logError(error, req, { operation: 'use_synced_subtitles', movieId });
    if (!res.headersSent) res.status(500).json({ error: error.message });
  }
});

// GET /transfers — Drive <-> Azure copy jobs of this movie (not hidden).
// Failed or cancelled imports are left out once the file is in Azure anyway
// (uploaded by hand or imported later): they no longer need attention.
router.get('/transfers', async (req, res) => {
  const { movieId } = req.params;
  try {
    const result = await pool.query(
      `SELECT j.* FROM movie_file_transfer_jobs j
       WHERE j.movie_id = $1 AND j.dismissed_at IS NULL
         AND NOT (
           j.direction = 'drive_to_azure'
           AND j.status IN ('failed', 'cancelled')
           AND EXISTS (
             SELECT 1 FROM movie_files f
             WHERE f.movie_id = j.movie_id AND f.file_kind = j.file_kind AND f.storage = 'azure'
           )
         )
       ORDER BY j.created_at DESC LIMIT 20`,
      [movieId]
    );
    res.json({ jobs: result.rows });
  } catch (error) {
    logError(error, req, { operation: 'get_file_transfers', movieId });
    res.status(500).json({ error: error.message });
  }
});

// POST /transfers/:jobId/retry — re-run a failed/cancelled transfer.
router.post('/transfers/:jobId/retry', async (req, res) => {
  const { movieId, jobId } = req.params;
  try {
    const result = await pool.query(
      'SELECT * FROM movie_file_transfer_jobs WHERE id = $1 AND movie_id = $2',
      [jobId, movieId]
    );
    const old = result.rows[0];
    if (!old) return res.status(404).json({ error: 'Transfer not found' });
    if (!['failed', 'cancelled'].includes(old.status)) {
      return res.status(409).json({ error: 'Only failed or cancelled transfers can be retried' });
    }
    const row = await movieStorage.loadRow(movieId, old.file_kind);
    let sourceRef = old.source_ref;
    if (old.direction === 'azure_to_drive') {
      // Back up the master's current version, not the one that failed.
      if (!row || row.storage !== 'azure') {
        return res.status(400).json({ error: 'Nothing in Azure to back up' });
      }
      sourceRef = movieStorage.fileRef(row);
    } else {
      // An import may only be retried while the slot still holds what it was
      // meant to replace: the same legacy Drive row (automatic imports), or
      // nothing newer than the original request (explicit imports).
      const stillLegacy = !row || (row.storage === 'drive' && row.drive_file_id === old.source_ref);
      const untouched = !row || new Date(row.updated_at) <= new Date(old.created_at);
      if (!(old.replace_existing ? untouched : stillLegacy)) {
        return res.status(409).json({ error: 'The file was replaced since; this copy is no longer needed' });
      }
    }
    const job = await fileTransferQueue.enqueue({
      movieId,
      fileKind: old.file_kind,
      direction: old.direction,
      sourceRef,
      transcodeAfter: old.transcode_after,
      replaceExisting: old.replace_existing,
      createdBy: req.user?.email,
    });
    if (!job) return res.status(409).json({ error: 'This transfer is already running' });
    await pool.query('UPDATE movie_file_transfer_jobs SET dismissed_at = CURRENT_TIMESTAMP WHERE id = $1', [
      jobId,
    ]);
    res.status(201).json({ job });
  } catch (error) {
    logError(error, req, { operation: 'retry_file_transfer', movieId });
    res.status(500).json({ error: error.message });
  }
});

// POST /transfers/:jobId/dismiss — hide a finished transfer from the list.
router.post('/transfers/:jobId/dismiss', async (req, res) => {
  const { movieId, jobId } = req.params;
  try {
    await pool.query(
      `UPDATE movie_file_transfer_jobs SET dismissed_at = CURRENT_TIMESTAMP
       WHERE id = $1 AND movie_id = $2 AND status NOT IN ('pending', 'running')`,
      [jobId, movieId]
    );
    res.json({ message: 'Hidden' });
  } catch (error) {
    logError(error, req, { operation: 'dismiss_file_transfer', movieId });
    res.status(500).json({ error: error.message });
  }
});

// POST /backup — (re)create the Drive backup of the Azure master.
router.post('/backup', async (req, res) => {
  const { movieId } = req.params;
  if (!fileTransferQueue.isConfigured()) {
    return res.status(503).json({ error: 'Transfers are not configured' });
  }
  try {
    const row = await movieStorage.loadRow(movieId, 'movie');
    if (!row || row.storage !== 'azure') {
      return res.status(400).json({ error: 'The movie file is not in Azure' });
    }
    const job = await fileTransferQueue.enqueueBackup(row, { createdBy: req.user?.email });
    if (!job) return res.status(409).json({ error: 'A backup is already running' });
    res.status(201).json({ job });
  } catch (error) {
    logError(error, req, { operation: 'backup_movie_file', movieId });
    res.status(500).json({ error: error.message });
  }
});

// PUT /ready — set or clear the manual "files ready" mark ({ ready: bool }).
router.put('/ready', async (req, res) => {
  const { movieId } = req.params;
  try {
    const ready = req.body?.ready === true;
    const result = await pool.query(
      `UPDATE movies SET files_ready_at = $2, files_ready_by = $3
       WHERE id = $1 RETURNING files_ready_at, files_ready_by`,
      [movieId, ready ? new Date() : null, ready ? req.user?.email || null : null]
    );
    if (result.rows.length === 0) return res.status(404).json({ error: 'Movie not found' });
    await auditFileChange(req, 'set_files_ready', { action: 'UPDATE', extra: { ready } });
    res.json({ ready: readyOf(result.rows[0]) });
  } catch (error) {
    logError(error, req, { operation: 'set_movie_files_ready', movieId });
    res.status(500).json({ error: error.message });
  }
});

// DELETE /:fileKind — drop the row. Azure: the blob is deleted (recoverable
// for 14 days via soft delete). The Drive copy is trashed, or renamed to
// {name}.removed.{ext} — the folder scan that runs on every page load would
// otherwise re-adopt it by its convention name and the asset would come back.
router.delete('/:fileKind', async (req, res) => {
  const { movieId, fileKind } = req.params;
  const removeFromDrive = req.query.remove_from_drive === 'true';
  try {
    if (!FILE_KINDS.includes(fileKind)) {
      return res.status(400).json({ error: 'Invalid file kind' });
    }
    const row = await movieStorage.loadRow(movieId, fileKind);
    if (!row) return res.status(404).json({ error: 'File not found' });

    const active = await pool.query(
      `SELECT id FROM movie_file_transfer_jobs
       WHERE movie_id = $1 AND file_kind = $2 AND status IN ('pending', 'running')`,
      [movieId, fileKind]
    );
    if (active.rows.length > 0) {
      return res.status(409).json({ error: 'A copy of this file is in progress; try again when it finishes' });
    }

    let renamedTo = null;
    if (row.drive_file_id) {
      if (googleDrive.isConfigured()) {
        renamedTo = await detachDriveCopy(row.drive_file_id, { trash: removeFromDrive });
      } else if (removeFromDrive) {
        return notConfigured(res);
      }
    }
    if (row.storage === 'azure') {
      await movieStorage.deleteBlob(row.blob_name);
    }

    await pool.query(
      'DELETE FROM movie_files WHERE movie_id = $1 AND file_kind = $2',
      [movieId, fileKind]
    );
    if (fileKind.startsWith('subtitles_')) {
      await staleOpenFlags(req, movieId, fileKind.replace('subtitles_', ''));
    }
    await auditFileChange(req, 'delete', {
      before: row,
      action: 'DELETE',
      extra: { trashed_on_drive: removeFromDrive, renamed_to: renamedTo },
    });
    res.json({ message: 'File removed', trashed: removeFromDrive, renamed_to: renamedTo });
  } catch (error) {
    logError(error, req, { operation: 'delete_movie_file', movieId });
    res.status(500).json({ error: error.message });
  }
});

module.exports = router;
